# Generated by Django 5.0.1 on 2024-02-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('bloodbank_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bloodbank_location', models.CharField(max_length=100)),
                ('bloodbank_phone', models.CharField(max_length=10)),
                ('Opositive_units', models.IntegerField()),
                ('Onegative_units', models.IntegerField()),
                ('Apositive_units', models.IntegerField()),
                ('Anegative_units', models.IntegerField()),
                ('Bpositive_units', models.IntegerField()),
                ('Bnegative_units', models.IntegerField()),
                ('ABpositive_units', models.IntegerField()),
                ('ABnegative_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_name', models.CharField(max_length=30)),
                ('donor_photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('donor_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('donor_phone', models.CharField(max_length=10)),
                ('last_donation_date', models.DateField()),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_app.bloodbank')),
                ('donor_blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_app.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_app.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_app.donor')),
            ],
        ),
    ]
