# Generated by Django 5.0.1 on 2024-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_app', '0002_alter_donor_donor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='Onegative_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
