# Generated by Django 5.0.1 on 2024-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_app', '0003_alter_bloodbank_onegative_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='Opositive_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
