# Generated by Django 5.0.1 on 2024-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_app', '0005_alter_bloodbank_abnegative_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(default=None),
        ),
    ]
